### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by philpax** [setzer22/llama-rs#19]
It should be pretty straightforward to set up CI on [Windows|Linux|macOS] x86-64 and macOS ARM64. It should also help us test porting over the remaining build flags from the original Makefile.

**Comment by setzer22** [comment]
It will not be possible to run tests, however, because I don't think we can put the weights on the CI server. But still, something to just verify it compiles on multiple architectures would be pretty good already.

I generally also add clippy and rustfmt checks in my projects, but I'm open to be convinced otherwise. I'd say at least rustfmt is necessary. Too many people use format-on-save and it tends to ruin diffs if you don't enforce formatting on CI.
